yatube/about/urls.py
from django.urls import path
from about import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import AutoDateModel

User = get_user_model()


class Post(AutoDateModel):
    text = models.TextField('Текст поста', help_text="Введите текст поста")
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='groups',
        verbose_name='Group',
        help_text="Группа, к которой будет относиться пост",
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self) -> str:
        return f'{self.text[:15]}'

    class Meta:
        ordering = ('-pub_date',)


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return f'{self.title}'


class Comment(AutoDateModel):
    text = models.TextField('Текст комментария')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='comments',
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self) -> str:
        return f'{self.text}'


class Follow(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=['author', 'user'],
            name='unique_author_user'
        )]

yatube/posts/forms.py
from django import forms

from posts.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from posts.forms import CommentForm, PostForm
from posts.models import Follow, Group, Post, User
from yatube.settings import NUMBER_POSTS_PER_PAGE


def index(request: HttpRequest) -> HttpResponse:
    """Home page."""
    posts = Post.objects.select_related('group').select_related('author').all()
    context = {
        'title': 'Последние обновления на сайте',
        'page_obj': create_paginator(request, posts),
        'index': True
    }
    template = 'posts/index.html'
    return render(request, template, context)


def group_posts(request: HttpRequest, slug: str) -> HttpResponse:
    """Page to display posts of one group."""
    group = get_object_or_404(Group, slug=slug)
    posts = group.groups.select_related('author').all()
    context = {
        'group': group,
        'page_obj': create_paginator(request, posts),
    }
    template = 'posts/group_list.html'
    return render(request, template, context)


def profile(request: HttpRequest, username: str) -> HttpResponse:
    """User information page."""
    user = get_object_or_404(User, username=username)
    posts = user.posts.select_related('group').all()
    following = None
    if request.user.is_authenticated:
        sub = Follow.objects.filter(author=user, user=request.user)
        following = True if sub else False
    context = {
        'posts_count': posts.count(),
        'page_obj': create_paginator(request, posts),
        'username': user,
        'following': following,
    }
    template = 'posts/profile.html'
    return render(request, template, context)


def post_detail(request: HttpRequest, post_id: int) -> HttpResponse:
    """Page to display post details."""
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    posts_count = post.author.posts.all().count()
    form = CommentForm()
    context = {
        'post': post,
        'title': post.text[:29],
        'posts_count': posts_count,
        'form': form,
        'comments': comments,
    }
    template = 'posts/post_detail.html'
    return render(request, template, context)


@login_required
def post_create(request: HttpRequest) -> HttpResponse:
    """Page to create a new post for logged in users."""
    if request.method != 'POST':
        form = PostForm()
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm(
        request.POST,
        files=request.FILES or None,
    )
    if form.is_valid():
        save_form_to_db(form, request.user)
        return redirect('posts:profile', username=request.user.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request: HttpRequest, post_id: int) -> HttpResponse:
    """Page to edit a post for logged in user."""
    post = get_object_or_404(Post, pk=post_id)
    if request.method != 'POST' and post.author == request.user:
        form = PostForm(instance=post)
        context = {
            'form': form,
            'is_edit': True,
        }
        return render(request, 'posts/create_post.html', context)
    if request.method != 'POST' and post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST,
        instance=post,
        files=request.FILES or None,
    )
    if form.is_valid():
        save_form_to_db(form, request.user)
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def add_comment(request: HttpRequest, post_id: int) -> HttpResponse:
    """Add a comment to a post by an authorized user."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """"Subscription page."""
    posts = Post.objects.filter(
        author__following__user=request.user
    ).select_related('group').select_related('author')
    context = {
        'title': 'Подписки',
        'page_obj': create_paginator(request, posts),
        'follow': True,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Add author to subscriptions."""
    user = get_object_or_404(User, username=username)
    if user == request.user:
        return redirect('posts:profile', username=username)
    Follow.objects.get_or_create(
        author=user,
        user=request.user,
    )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Remove author from subscriptions."""
    user = get_object_or_404(User, username=username)
    sub = Follow.objects.filter(author=user, user=request.user)
    sub.delete()
    return redirect('posts:profile', username=username)


def save_form_to_db(form: PostForm, user: User) -> None:
    """"Save post to DB."""
    post = form.save(commit=False)
    post.text = form.cleaned_data['text']
    post.group = form.cleaned_data['group']
    post.author = user
    post.save()


def create_paginator(request: HttpRequest, posts: Post) -> Paginator:
    """Create paginator"""
    paginator = Paginator(posts, NUMBER_POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    <title>Редактировать запись</title>
  {% else %}
    <title>Новый пост {{ user.get_full_name }}</title>
  {% endif %}
  {% endblock %}
{% block content %}   
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">   
            {% if is_edit %}
              Редактировать запись
            {% else %}
              Новый пост
            {% endif %}                 
          </div>
          <div class="card-body">        
            <form method="post" enctype="multipart/form-data">
              {% load user_filters %}
              {% csrf_token %}
              {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endif %}
              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>    
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}  
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block content %}
  {% load cache %}   
  {% load thumbnail %}
    <div class="container py-5">     
      <h1>Последние обновления на сайте</h1>
      {% include 'posts/includes/switcher.html' %}
      {% if not page_obj %}<h3>Nothing to see here</h3>{% endif %}
        {% for post in page_obj %}  
        {% include 'posts/includes/post_display.html' %}
          {% if post.group %}   
            <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
          {% else %}
            <a href="">все записи группы</a>
          {% endif %}   
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
      {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  <title>{{ group.title }}</title>
{% endblock %}
{% block content %}
  {% load thumbnail %}
  <div class="container py-5">        
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>    
    {% for post in page_obj %}    
    {% include 'posts/includes/post_display.html' %} 
      <a href="">все записи группы</a>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
  {% load cache %}   
    <div class="container py-5">     
      <h1>Последние обновления на сайте</h1>
      {% include 'posts/includes/switcher.html' %}
      {% cache 20 index_page request.GET.page %}
        {% for post in page_obj %}  
          {% include 'posts/includes/post_display.html' %}
          {% if post.group %}   
            <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
          {% else %}
            <a href="">все записи группы</a>
          {% endif %}   
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        {% include 'posts/includes/paginator.html' %}
      </div>
    {% endcache %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}<title>Пост {{ title }}</title>{% endblock %}
{% block content %}
  {% load thumbnail %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:'d E Y' }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{post.group}}
              <a href="{% url 'posts:group' post.group.slug %}">
                 все записи группы
              </a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span>{{ posts_count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p> 
        {% if user.username == post.author.get_username %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
            редактировать запись
          </a> 
        {% endif %}
        {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}
        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
                <p>
                  {{ comment.text }}
                </p>
              </div>
            </div>
        {% endfor %} 
      </article>  
    </div>
  </div>
{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}<title>Профайл пользователя {{ username.get_full_name }}</title>{% endblock %}
{% block content %}
  {% load thumbnail %}
  <div class="container py-5">
    {% if user.is_authenticated and user != username %}
      <div class="mb-5">        
        <h1>Все посты пользователя {{ username.get_full_name }}</h1>
        <h3>Всего постов: {{ posts_count }}</h3>
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      </div>
    {% endif %}
    {% for post in page_obj %}   
      <article>
        <ul>
         <li>
            Дата публикации: {{ post.pub_date|date:'d E Y' }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>  
        <a href="{% url 'posts:post_detail' post.pk %}">
          подробная информация
        </a> 
      </article>  
      {% if post.group %}   
        <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
      {% else %}
        <a href="">все записи группы</a>
      {% endif %}  
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %} 